### ISSUE TITLE
Error if database does not exist (mysql-driver)

### ISSUE THREAD

**Issue by vpeil** [LibreCat/Catmandu-DBI#8]
Here's my catmandu.yml (tested with the mysql driver)

```yaml
store:
  default:
    package: DBI 
    options:
      data_source: "DBI:mysql:database=test"
      username: whoami
      password: secret
```

The command
```bash
$ echo '{"hello" : "world"}' | catmandu import
```

dies with **no database exists**. Is this behaviour intentional? In case of Elasticsearch the index gets created if needed. Should we add here a "create database $name"?
